trigger: none
pr:
  branches:
    include:
      - "*"
  drafts: false
  
pool:
  vmImage: ubuntu-latest

steps:
- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)/terraform'
  inputs:
    Contents:  |
      **/modules/**
      main.tf
      variables.tf
      terraform.tfvars
    TargetFolder: '$(build.artifactstagingdirectory)/terraform'
- task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
  displayName: 'Install terraform'
  inputs:
    terraformVersion: '1.1.7' 

- task: TerraformTaskV2@2
  displayName: 'terraform validate'
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: '$(build.artifactstagingdirectory)/terraform'
