trigger:
  - develop

pool:
  vmImage: ubuntu-latest

steps:
- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)/terraform'
  inputs:
    Contents:  |
      **/modules/**
      **/stage/**
    TargetFolder: '$(build.artifactstagingdirectory)/terraform'

- task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
  displayName: 'Install terraform'
  inputs:
    terraformVersion: '1.1.7' 

- task: TerraformCLI@0
  inputs:
    command: 'init'
    allowTelemetryCollection: true

- task: TerraformCLI@0
  inputs:
    command: 'validate'
    allowTelemetryCollection: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/terraform' 