# trigger: none

# resources:
#  pipelines:
#    - pipeline: terra-review-ci
#      source: terra-review
#      trigger: true


variables:
- group: 'terraform.prod.unleash'

pool:
  vmImage: ubuntu-latest

stages:
 - stage: Plan
   jobs:
   - job: Plan
     steps:
      - task: DownloadBuildArtifacts@1
        inputs:
          buildType: 'specific'
          project: 'df19d7ad-38d0-4f00-bfe3-4fab0e053dba'
          pipeline: '13'
          specificBuildWithTriggering: true
          buildVersionToDownload: 'latest'
          downloadType: 'single'
          artifactName: 'drop'
          downloadPath: '$(System.ArtifactsDirectory)'
      - task: replacetokens@5
        inputs:
          rootDirectory: '$(System.ArtifactsDirectory)/drop/review/unleash-app'
          targetFiles: 'terraform.tfvars'
          encoding: 'auto'
          tokenPattern: 'default'
          writeBOM: true
          actionOnMissing: 'fail'
          keepToken: false
          actionOnNoFiles: 'fail'
          enableTransforms: false
          enableRecursion: false
          useLegacyPattern: false
          useLegacyEmptyFeature: false
          enableTelemetry: false
      - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
        displayName: "Install terraform"
        inputs:
          terraformVersion: "1.1.7"

      - task: TerraformTaskV2@2
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(System.ArtifactsDirectory)/drop/review/unleash-app'
          backendServiceArm: '$(backendServiceArm)'
          backendAzureRmResourceGroupName: '$(backendAzureRmResourceGroupName)'
          backendAzureRmStorageAccountName: '$(backendAzureRmStorageAccountName)'
          backendAzureRmContainerName: '$(backendAzureRmContainerName)'
          backendAzureRmKey: '$(backendAzureRmKey)'

      - task: TerraformTaskV2@2
        inputs:
          provider: 'azurerm'
          command: 'validate'
          workingDirectory: '$(System.ArtifactsDirectory)/drop/review/unleash-app'

      - task: TerraformTaskV2@2
        inputs:
          provider: 'azurerm'
          command: 'plan'
          workingDirectory: '$(System.ArtifactsDirectory)/drop/review/unleash-app'
          commandOptions: '-out=tfplan -input=false'
          environmentServiceNameAzureRM: 'Azure subscription 1(5ccd862b-7710-4536-85dd-a425a1b28173)'
 - stage: Deploy
   dependsOn: Plan
   condition: succeeded('Plan')
   jobs:
   - job: Deploy
     displayName: Wait for external validation  
     timeoutInMinutes: 4320 # job times out in 3 days
     steps:   
      - task: ManualValidation@0
        timeoutInMinutes: 1440 # task times out in 1 day
        inputs:
            notifyUsers: |
                v.dedyulya@itransition.com
            instructions: 'Please validate the build configuration and resume'
            onTimeout: 'reject'
      - task: TerraformTaskV2@2
        inputs:
          provider: 'azurerm'
          command: 'apply'
          workingDirectory: '$(System.ArtifactsDirectory)/drop/review/unleash-app'
          commandOptions: '-input=false tfplan'
          environmentServiceNameAzureRM: 'Azure subscription 1(5ccd862b-7710-4536-85dd-a425a1b28173)'