# resources:
#  pipelines:
#    - pipeline: terraform-review-ci
#      source: Terraform - Review
#      trigger:
#       branches:
#         include:
#         - develop

# variables:
# - group: 'terraform.prod.unleash'

# pool:
#   vmImage: ubuntu-latest

# jobs:
# - job: Plan
#   displayName: Plan Unleash App Infrastructure
#   steps:
#   - download: terraform-review-ci
#     artifact: drop
#   - task: replacetokens@5
#     inputs:
#       # rootDirectory: '$(System.ArtifactsDirectory)/drop/review/unleash-app'
#       rootDirectory: '$(PIPELINE.WORKSPACE)/terraform-review-ci/drop/review/unleash-app'
#       targetFiles: 'terraform.tfvars'
#       encoding: 'auto'
#       tokenPattern: 'default'
#       writeBOM: true
#       actionOnMissing: 'fail'
#       keepToken: false
#       actionOnNoFiles: 'fail'
#       enableTransforms: false
#       enableRecursion: false
#       useLegacyPattern: false
#       useLegacyEmptyFeature: false
#       enableTelemetry: false
#   - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
#     displayName: "Install terraform"
#     inputs:
#       terraformVersion: "1.1.7"
#   - task: TerraformTaskV2@2
#     inputs:
#       provider: 'azurerm'
#       command: 'init'
#       workingDirectory: '$(PIPELINE.WORKSPACE)/terraform-review-ci/drop/review/unleash-app'
#       backendServiceArm: '$(backendServiceArm)'
#       backendAzureRmResourceGroupName: '$(backendAzureRmResourceGroupName)'
#       backendAzureRmStorageAccountName: '$(backendAzureRmStorageAccountName)'
#       backendAzureRmContainerName: '$(backendAzureRmContainerName)'
#       backendAzureRmKey: '$(backendAzureRmKey)'
#   - task: TerraformTaskV2@2
#     inputs:
#       provider: 'azurerm'
#       command: 'validate'
#       workingDirectory: '$(PIPELINE.WORKSPACE)/terraform-review-ci/drop/review/unleash-app'
#   - task: TerraformTaskV2@2
#     inputs:
#       provider: 'azurerm'
#       command: 'plan'
#       workingDirectory: '$(PIPELINE.WORKSPACE)/terraform-review-ci/drop/review/unleash-app'
#       commandOptions: '-out=tfplan -input=false'
#       environmentServiceNameAzureRM: '$(backendServiceArm)'
#   - publish: '$(PIPELINE.WORKSPACE)/terraform-review-ci/drop'
#     artifact: unleash-dev-plan

# - job: waitForValidation
#   pool: server
#   displayName: Wait for validation  
#   timeoutInMinutes: 4320 # job times out in 3 days
#   steps:   
#   - task: ManualValidation@0
#     timeoutInMinutes: 1440 # task times out in 1 day
#     inputs:
#         notifyUsers: |
#             v.dedyulya@itransition.com
#         instructions: 'Please validate the build configuration and resume'
#         onTimeout: 'reject'
#   dependsOn: Plan

# - job: Deploy
#   displayName: Deploy Unleash App Infrastructure
#   steps:
#     - download: current
#       artifact: unleash-dev-plan
#     # - task: DownloadBuildArtifacts@1
#     #   inputs:
#     #    buildType: 'current'
#     #    downloadType: 'single'
#     #    artifactName: 'unleash-dev-plan'
#     #    downloadPath: '$(System.ArtifactsDirectory)'
#     - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
#       displayName: "Install terraform"
#       inputs:
#         terraformVersion: "1.1.7"
#     - task: Bash@3
#       inputs:
#         targetType: 'inline'
#         script: |
#           chmod -R a+x ./.terraform/providers/*
#         workingDirectory: '$(PIPELINE.WORKSPACE)/unleash-dev-plan/review/unleash-app'
#         # workingDirectory: '$(System.ArtifactsDirectory)/unleash-dev-plan/review/unleash-app'

#     - task: TerraformTaskV2@2
#       inputs:
#         provider: 'azurerm'
#         command: 'apply'
#         workingDirectory: '$(PIPELINE.WORKSPACE)/unleash-dev-plan/review/unleash-app'
#         # workingDirectory: '$(System.ArtifactsDirectory)/unleash-dev-plan/review/unleash-app'
#         commandOptions: '-input=false tfplan'
#         environmentServiceNameAzureRM: '$(backendServiceArm)'
#   dependsOn: waitForValidation
#   condition: succeeded()  

trigger:
  - develop # Define trigger branch

variables:
- group: 'terraform.prod.unleash' # Define variables group name
- name: tf_folder
  value: '$(build.artifactstagingdirectory)/terraform'
- name: env
  value: 'review' # Define environment
- name: app
  value: 'unleash-app' # Define app name
- name: artifact_name
  value: '$(app)-$(env)-artifact'

pool:
  vmImage: ubuntu-latest

stages:
- stage: Plan 
  displayName: 'Plan Infrastructure'
  jobs:
  - job: Plan
    displayName: 'Plan Infrastructure'
    steps:
    - task: CopyFiles@2
      displayName: 'Copy Files to: $(tf_folder)'
      inputs:
        Contents: |
          **/modules/**
          **/$(env)/**
        TargetFolder: '$(tf_folder)'
    - task: replacetokens@5
      displayName: 'Replace $(app)-$(env) variables'
      inputs:
        rootDirectory: '$(tf_folder)/$(env)/$(app)'
        targetFiles: 'terraform.tfvars'
        encoding: 'auto'
        tokenPattern: 'default'
        writeBOM: true
        actionOnMissing: 'fail'
        keepToken: false
        actionOnNoFiles: 'fail'
        enableTransforms: false
        enableRecursion: false
        useLegacyPattern: false
        useLegacyEmptyFeature: false
        enableTelemetry: false
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
      displayName: 'Install terraform 1.1.7'
      inputs:
        terraformVersion: "1.1.7"
    - task: TerraformTaskV2@2
      displayName: 'terraform init $(app)-$(env)'
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(tf_folder)/$(env)/$(app)'
        backendServiceArm: 'Azure subscription 1(5ccd862b-7710-4536-85dd-a425a1b28173)'
        backendAzureRmResourceGroupName: 'Shared'
        backendAzureRmStorageAccountName: 'tfstatestore2134'
        backendAzureRmContainerName: 'terraform'
        backendAzureRmKey: '$(env)/$(app)/terraform.tfstate'
    - task: TerraformTaskV2@2
      displayName: 'terraform validate $(app)-$(env)'
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: '$(tf_folder)/$(env)/$(app)'
    - task: TerraformTaskV2@2
      displayName: 'terraform plan $(app)-$(env)'
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(tf_folder)/$(env)/$(app)'
        commandOptions: '-out=tfplan -input=false'
        environmentServiceNameAzureRM: '$(backendServiceArm)'
    - publish: '$(tf_folder)'
      artifact: $(artifact_name)

- stage: Deploy
  displayName: 'Deploy Infrastructure'
  jobs:
  - job: waitForValidation
    pool: server
    displayName: 'Wait for validation'
    timeoutInMinutes: 4320 # job times out in 3 days
    steps:   
    - task: ManualValidation@0
      displayName: 'Wait for validation'
      timeoutInMinutes: 1440 # task times out in 1 day
      inputs:
          notifyUsers: |
              v.dedyulya@itransition.com
          instructions: 'Please validate the build configuration and resume'
          onTimeout: 'reject'
  - job: Deploy
    displayName: 'Deploy Infrastructure'
    steps:
      - download: current
        artifact: $(artifact_name)
      - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
        displayName: 'Install terraform 1.1.7'
        inputs:
          terraformVersion: "1.1.7"
      - task: Bash@3
        displayName: 'Change permissions for .terraform directory'
        inputs:
          targetType: 'inline'
          script: |
            chmod -R a+x ./.terraform/providers/*
          workingDirectory: '$(PIPELINE.WORKSPACE)/$(artifact_name)/$(env)/$(app)'
      - task: TerraformTaskV2@2
        displayName: 'terraform apply $(app)-$(env)'
        inputs:
          provider: 'azurerm'
          command: 'apply'
          workingDirectory: '$(PIPELINE.WORKSPACE)/$(artifact_name)/$(env)/$(app)'
          commandOptions: '-input=false tfplan'
          environmentServiceNameAzureRM: '$(backendServiceArm)'
    dependsOn: waitForValidation
  dependsOn: Plan  