<<<<<<< HEAD
rgname                    = "node-app"
plan_name                 = "app-plan-unleash1rq"
app_plan_kind             = "linux"
sku_size                  = "S1"
sku_tier                  = "Standard"
reserved                  = "true"
location                  = "eastus"
app_name                  = "unleash-app-qwe"
postgresql-server-name    = "unleash-postgresql-11f"
postgresql-database-name  = "unleash"
postgresql-admin-login    = "postgres"
postgresql-admin-password = "postrgesQ354"
charset                   = "utf8"
collation                 = "English_United States.1252"
postgresql-version        = "13"
postgresql-sku-name       = "B_Standard_B2s"
postgresql-storage        = "32768"

=======
>>>>>>> ae79986db1e0b94d9a7277bca7cadc1de75530ae
rgname                    = "#{ResourceGroupName}#"
plan_name                 = "#{AppPlanName}#"
app_plan_kind             = "#{AppPlanKind}#"
sku_size                  = "#{AppPlanSkuSize}#"
sku_tier                  = "#{AppPlanSkuTire}#"
reserved                  = "#{AppPlanReserved}#"
location                  = "#{LocationResources}#"
app_name                  = "#{AppServiceName}#"
postgresql-server-name    = "#{PostgresQLServerName}#"
postgresql-database-name  = "#{PostgreSQLDatabaseName}#"
postgresql-admin-login    = "#{PostgreSQLAdminLogin}#"
postgresql-admin-password = "#{PostgreSQLAdminPassword}#"
charset                   = "#{DBCharset}#"
collation                 = "#{DBCollation}#"
postgresql-version        = "#{PostgreSQlVersion}#"
postgresql-sku-name       = "#{PostgreSQlSKUName}#"
postgresql-storage        = "#{PostgreSQlStorage}#"
